export const CATEGORIES = {
  EXPENSE: [
    'Food & Dining',
    'Shopping',
    'Transportation',
    'Entertainment',
    'Utilities',
    'Healthcare',
    'Education',
    'EMI',
    'Rent',
    'Insurance',
    'Investment',
    'Uncategorized',
  ],
  INCOME: [
    'Salary',
    'Business',
    'Investment',
    'Freelance',
    'Gift',
    'Other',
  ],
};

export const CATEGORY_ICONS: { [key: string]: string } = {
  'Food & Dining': '🍽️',
  'Shopping': '🛒',
  'Transportation': '🚗',
  'Entertainment': '🎬',
  'Utilities': '💡',
  'Healthcare': '🏥',
  'Education': '📚',
  'EMI': '💳',
  'Rent': '🏠',
  'Insurance': '🛡️',
  'Investment': '📈',
  'Salary': '💰',
  'Business': '💼',
  'Freelance': '💻',
  'Gift': '🎁',
  'Other': '📝',
  'Uncategorized': '❓',
  'Electricity' : '⚡',
  'Water' : '💧',
  'Internet' : '🌐',
  'Phone' : '📱',
  'Subscription' : '📺'
};
